# Generated by Django 3.2.3 on 2021-05-26 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='date',
        ),
    ]
